### ISSUE TITLE
ed25519-java don't include the license file

### ISSUE THREAD

**Issue by puntogil** [str4d/ed25519-java#11]
Not available LICENSE file in source directory structure
Please. Added license and copyright notice.
the fedora pakaging guideline is very strictly precise about this problem
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Text
thanks
regards

**Comment by str4d** [comment]
I'm unsure of what I need to do. The README clearly states that the code is released into the Public Domain, and therefore there is no license text to include. The guide does only say that upstream should be "encouraged", not required, to include license text if it is not a requirement of the license.

Could you please clarify how the License Text section of the Licensing Guide interacts with the [Public Domain section](https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#Public_Domain)?

**Comment by puntogil** [comment]
Hi
talking with our staff that takes care of these issues, we have concluded that it is no longer necessary to add the license file. although other projects with the same do
regards

**Comment by dllud** [comment]
@str4d It's standard practice to add a LICENSE file even if you want to release it for Public Domain. Having such file is really helpful for upstream packagers and will avoid issues like this one.

If you want to place it under Public Domain go with one of the following "licenses": [The Unlicense](http://choosealicense.com/licenses/unlicense/) or [Creative Commons Zero](http://choosealicense.com/licenses/cc0-1.0/).

**Comment by puntogil** [comment]
as e.g.  see https://github.com/davidB/scala-maven-plugin/blob/master/UNLICENSE

**Comment by str4d** [comment]
@dllud thanks, this is exactly what I was asking about.

Based on my further reading, [Unlicense has significant issues](https://lists.opensource.org/pipermail/license-review/2012-January/000052.html), but [CC0 appears to be alright for software](https://wiki.creativecommons.org/wiki/CC0_FAQ#May_I_apply_CC0_to_computer_software.3F_If_so.2C_is_there_a_recommended_implementation.3F), and is what I shall go for.

Just to ensure that all the legal boxes are ticked off: **If you are one of the 6 contributors, do you consent to this change in license?** If so, please leave a comment on this issue saying 'yes' or 'lgtm' or however you typically express consent.

I expect no one to have any issues, as this repo has been marked as public domain since before I forked it from @k3d3 (the fork is why you're included here btw, even though none of your code is actually in this implementation :P), so it's not *really* a change in license, but I want to make sure everything is kosher.

- [x] @str4d
- [ ] @BloodyRookie
- [ ] @pmarches
- [ ] @k3d3
- [ ] @mbakkar
- [ ] @majestrate

**Comment by pmarches** [comment]
Yes, of course

**Comment by majestrate** [comment]
Works fine.

**Comment by BloodyRookie** [comment]
ok for me.

**Comment by mbakkar** [comment]
yes

**Comment by mbakkar** [comment]
yes, woops

**Comment by k3d3** [comment]
sorry for the late response, I'm good for a license change

**Comment by str4d** [comment]
Woop, that's everyone!
